version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fleamarket
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    hostname: postgres
    restart: always
    user: root
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d
      - ./docker/postgres/data:/var/lib/postgresql/data
